#! /bin/sh

xcompmgr &
nitrogen --restore &
# wmname LG3D &

gnome-terminal &
sxhkd &

# if [ $(xrandr --query | grep ' connected' | wc -l) -eq 1 ]
# then
#     bspc monitor eDP -d w1 s2 a3 b4 c5 w6 s7 a8 b9 c0
# else
#     bspc monitor eDP -d w1 s2 a3 b4 c5
#     bspc monitor HDMI-A-0 -d w6 s7 a8 b9 c0
# fi

bspc monitor eDP -d w1 s2 a3 b4 c5
bspc monitor HDMI-A-0 -d w6 s7 a8 b9 c0

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='V' state=floating follow=on
bspc rule -a Chromium desktop='I'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

pkill polybar

$HOME/.config/polybar/launch.sh
